GET http://localhost:8080/v1/eventz?page=0&size=50

###
#Get by id
GET http://localhost:8080/v1/eventz/2009
###
POST http://localhost:8080/v1/eventz
Content-Type: application/json
Cookie: key=first-value

{
  "title": "Internal Hackathon",
  "description": "24-hour hackathon to promote innovation",
  "location": "Innovation Lab",
  "date": 1673370000000
}

###
#Update existing event
PUT http://localhost:8080/v1/eventz/10
Content-Type: application/json
Cookie: key=first-value

{
  "title": "Training Workshop 3",
  "description": "Training session on new software tools",
  "location": "Training Room 3",
  "date": 1733754984000
}

###
DELETE http://localhost:8080/v1/eventz/{id}

###
#Search Events by title
GET http://localhost:8080/v1/eventz/filter?title=concert&page=0&size=10

###
#Search by date
GET http://localhost:8080/v1/eventz/date?eventDate=1673370000000

###
#Search Events by location
GET http://localhost:8080/v1/eventz/filter?location=room&page=0&size=10

###
#Search Events by title and location
GET http://localhost:8080/v1/eventz/filter?title=hackaton&location=room&page=0&size=10

###
#Filter Events by Category
GET http://localhost:8080/v1/eventz?category=music&page=0&size=10

###
#Upcoming Events:
GET http://localhost:8080/v1/eventz/upcoming?page=0&size=10