#Register
POST http://localhost:8080/v1/auth/register
Content-Type: application/json
Cookie: key=first-value

{
  "email": "jone@gmail.io",
  "password": "123456",
  "firstName": "Any",
  "lastName": "Flow",
  "role": "ADMIN"
}

###
#login
POST http://localhost:8080/v1/auth/login
Content-Type: application/json
Cookie: key=first-value

{
  "email": "admin@gmail.io",
  "password": "123456"
}

###
#Get current user
GET http://localhost:8080/v1/users/current-user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyNDAyMjEyMiwiZXhwIjoxNzI0MDI5MzIyfQ.hjIYfBLgJDY_7y34zNz5m1DdRt-dFISYuMw3OUxcPEo


###
GET http://localhost:8080/v1/events?page=0&size=50
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyNDE5MjYxMSwiZXhwIjoxNzI0MTk2MjExfQ.i4y-j8FDWmHTAFnBlFhAWwGv9OGGXfg6pa7Nle4lZXI


###
#Get by id
GET http://localhost:8080/v1/events/37
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NAZ21haWwuaW8iLCJpYXQiOjE3MjM4NTMzMzIsImV4cCI6MTcyMzg2MDUzMn0.4G1o0TgPwsX6WbccHM-Uo-YtHsmnS4tfujWydsMWDXo


###
#Create event
POST http://localhost:8080/v1/events
Content-Type: application/json
Cookie: key=first-value
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyNDAyMjMyNCwiZXhwIjoxNzI0MDI5NTI0fQ.230qeMx58vGL2YOXoUuqddKz9f2prMAKz1ZHS9SaJYs

{
  "title": "Company Hall",
  "description": "Quarterly town hall meeting for all employees",
  "location": "Main Auditorium",
  "date": 1753754984000
}

###
#Update existing event
#PUT http://localhost:8080/v1/events/37
PUT http://localhost:8080/v1/events/35
Content-Type: application/json
Cookie: key=first-value
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyNDAyMjMyNCwiZXhwIjoxNzI0MDI5NTI0fQ.230qeMx58vGL2YOXoUuqddKz9f2prMAKz1ZHS9SaJYs

{
  "title": "Client Demo",
  "description": "Demo of prototype to Client B",
  "location": "Client B's Office",
  "date": 1738754984000
}

###
DELETE http://localhost:8080/v1/events/admin/34
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyMzgwODc4NSwiZXhwIjoxNzIzODE1OTg1fQ.pa1kLOAB4YVRaYMUUZDtxVBtKzNkSKE2H9PUFSwgeOQ

###
#Search Events by title
GET http://localhost:8080/v1/events/filter?title=training&page=0&size=10

###
#Search by date
GET http://localhost:8080/v1/events/date?eventDate=1673370000000

###
#Search Events by location
GET http://localhost:8080/v1/events/filter?location=room&page=0&size=10

###
#Search Events by title and location
GET http://localhost:8080/v1/events/filter?title=training&location=room&page=0&size=10

###
#Filter Events by Category
GET http://localhost:8080/v1/events?category=music&page=0&size=10

###
#Upcoming Events:
GET http://localhost:8080/v1/events/upcoming?page=0&size=10

###
#Get all users
GET http://localhost:8080/v1/users?page=0&size=10

###
#register
POST http://localhost:8080/v1/auth/register

###
###
#login
POST http://localhost:8080/v1/auth/login
Content-Type: application/json
Cookie: key=first-value

{
  "email": "admin@gmail.io",
  "password": "123456"
}

###
#event-registration
POST http://localhost:8080/v1/event-registration/39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NAZ21haWwuaW8iLCJpYXQiOjE3MjQwMjYwNDcsImV4cCI6MTcyNDAzMzI0N30.rsE91-QhLchD9LFahnTfqO3gGbI7qaFwUhwfiFM_XQw


###
#cancel event-registration
POST http://localhost:8080/v1/event-registration/cancel/39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NAZ21haWwuaW8iLCJpYXQiOjE3MjQwMjYwNDcsImV4cCI6MTcyNDAzMzI0N30.rsE91-QhLchD9LFahnTfqO3gGbI7qaFwUhwfiFM_XQw


###
POST http://localhost:8080/v1/event-registration/remove-participant?participantId=4&eventId=39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NAZ21haWwuaW8iLCJpYXQiOjE3MjM5Nzg0MTAsImV4cCI6MTcyMzk4NTYxMH0.LaxVQyZsNzBJgqZVK9uy8b8LdZFjHx6CaafXVt956vQ



###
POST http://localhost:8080/v1/event-registration/add-participant?participantId=1&eventId=39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NAZ21haWwuaW8iLCJpYXQiOjE3MjM5Nzg0MTAsImV4cCI6MTcyMzk4NTYxMH0.LaxVQyZsNzBJgqZVK9uy8b8LdZFjHx6CaafXVt956vQ


###
#Admin add participant
POST http://localhost:8080/api/admin/event/add-participant?participantId=1&eventId=39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyNDA1ODQ4NSwiZXhwIjoxNzI0MDY1Njg1fQ.QcKxDjxx633f2YJS68tO305odBi9KU-0nsPdLM26Zwk

###
#Admin remove participant
POST http://localhost:8080/api/admin/event/remove-participant?participantId=1&eventId=39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5pbyIsImlhdCI6MTcyNDA1ODQ4NSwiZXhwIjoxNzI0MDY1Njg1fQ.QcKxDjxx633f2YJS68tO305odBi9KU-0nsPdLM26Zwk









